// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeadBeatMessage.proto

package com.openim.common.im.bean.protbuf;

public final class ProtobufHeadBeatMessage {
  private ProtobufHeadBeatMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeadBeatMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 headbeat = 1;
    boolean hasHeadbeat();
    int getHeadbeat();
  }
  public static final class HeadBeatMessage extends
      com.google.protobuf.GeneratedMessage
      implements HeadBeatMessageOrBuilder {
    // Use HeadBeatMessage.newBuilder() to construct.
    private HeadBeatMessage(Builder builder) {
      super(builder);
    }
    private HeadBeatMessage(boolean noInit) {}
    
    private static final HeadBeatMessage defaultInstance;
    public static HeadBeatMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public HeadBeatMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.internal_static_com_openim_common_im_bean_protbuf_HeadBeatMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.internal_static_com_openim_common_im_bean_protbuf_HeadBeatMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 headbeat = 1;
    public static final int HEADBEAT_FIELD_NUMBER = 1;
    private int headbeat_;
    public boolean hasHeadbeat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getHeadbeat() {
      return headbeat_;
    }
    
    private void initFields() {
      headbeat_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, headbeat_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, headbeat_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.internal_static_com_openim_common_im_bean_protbuf_HeadBeatMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.internal_static_com_openim_common_im_bean_protbuf_HeadBeatMessage_fieldAccessorTable;
      }
      
      // Construct using com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        headbeat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage.getDescriptor();
      }
      
      public com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage getDefaultInstanceForType() {
        return com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage.getDefaultInstance();
      }
      
      public com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage build() {
        com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage buildPartial() {
        com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage result = new com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.headbeat_ = headbeat_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage) {
          return mergeFrom((com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage other) {
        if (other == com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage.getDefaultInstance()) return this;
        if (other.hasHeadbeat()) {
          setHeadbeat(other.getHeadbeat());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              headbeat_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 headbeat = 1;
      private int headbeat_ ;
      public boolean hasHeadbeat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getHeadbeat() {
        return headbeat_;
      }
      public Builder setHeadbeat(int value) {
        bitField0_ |= 0x00000001;
        headbeat_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeadbeat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        headbeat_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.openim.common.im.bean.protbuf.HeadBeatMessage)
    }
    
    static {
      defaultInstance = new HeadBeatMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.openim.common.im.bean.protbuf.HeadBeatMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_openim_common_im_bean_protbuf_HeadBeatMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_openim_common_im_bean_protbuf_HeadBeatMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025HeadBeatMessage.proto\022!com.openim.comm" +
      "on.im.bean.protbuf\"#\n\017HeadBeatMessage\022\020\n" +
      "\010headbeat\030\001 \001(\005B\031B\027ProtobufHeadBeatMessa" +
      "ge"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_openim_common_im_bean_protbuf_HeadBeatMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_openim_common_im_bean_protbuf_HeadBeatMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_openim_common_im_bean_protbuf_HeadBeatMessage_descriptor,
              new java.lang.String[] { "Headbeat", },
              com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage.class,
              com.openim.common.im.bean.protbuf.ProtobufHeadBeatMessage.HeadBeatMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
