// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConnectMessage.proto

package com.openim.common.im.bean.protbuf;

public final class ProtobufConnectMessage {
  private ProtobufConnectMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConnectMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string loginId = 1;
    boolean hasLoginId();
    String getLoginId();
    
    // optional string password = 2;
    boolean hasPassword();
    String getPassword();
    
    // optional string serverQueue = 3;
    boolean hasServerQueue();
    String getServerQueue();
  }
  public static final class ConnectMessage extends
      com.google.protobuf.GeneratedMessage
      implements ConnectMessageOrBuilder {
    // Use ConnectMessage.newBuilder() to construct.
    private ConnectMessage(Builder builder) {
      super(builder);
    }
    private ConnectMessage(boolean noInit) {}
    
    private static final ConnectMessage defaultInstance;
    public static ConnectMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConnectMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.openim.common.im.bean.protbuf.ProtobufConnectMessage.internal_static_com_openim_common_im_bean_protbuf_ConnectMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.openim.common.im.bean.protbuf.ProtobufConnectMessage.internal_static_com_openim_common_im_bean_protbuf_ConnectMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string loginId = 1;
    public static final int LOGINID_FIELD_NUMBER = 1;
    private java.lang.Object loginId_;
    public boolean hasLoginId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getLoginId() {
      java.lang.Object ref = loginId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          loginId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLoginIdBytes() {
      java.lang.Object ref = loginId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        loginId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string serverQueue = 3;
    public static final int SERVERQUEUE_FIELD_NUMBER = 3;
    private java.lang.Object serverQueue_;
    public boolean hasServerQueue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getServerQueue() {
      java.lang.Object ref = serverQueue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          serverQueue_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getServerQueueBytes() {
      java.lang.Object ref = serverQueue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        serverQueue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      loginId_ = "";
      password_ = "";
      serverQueue_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLoginIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getServerQueueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLoginIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getServerQueueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.openim.common.im.bean.protbuf.ProtobufConnectMessage.internal_static_com_openim_common_im_bean_protbuf_ConnectMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.openim.common.im.bean.protbuf.ProtobufConnectMessage.internal_static_com_openim_common_im_bean_protbuf_ConnectMessage_fieldAccessorTable;
      }
      
      // Construct using com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        loginId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        serverQueue_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage.getDescriptor();
      }
      
      public com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage getDefaultInstanceForType() {
        return com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage.getDefaultInstance();
      }
      
      public com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage build() {
        com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage buildPartial() {
        com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage result = new com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loginId_ = loginId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serverQueue_ = serverQueue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage) {
          return mergeFrom((com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage other) {
        if (other == com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage.getDefaultInstance()) return this;
        if (other.hasLoginId()) {
          setLoginId(other.getLoginId());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasServerQueue()) {
          setServerQueue(other.getServerQueue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              loginId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              serverQueue_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string loginId = 1;
      private java.lang.Object loginId_ = "";
      public boolean hasLoginId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLoginId() {
        java.lang.Object ref = loginId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          loginId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLoginId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        loginId_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoginId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loginId_ = getDefaultInstance().getLoginId();
        onChanged();
        return this;
      }
      void setLoginId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        loginId_ = value;
        onChanged();
      }
      
      // optional string password = 2;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
      }
      
      // optional string serverQueue = 3;
      private java.lang.Object serverQueue_ = "";
      public boolean hasServerQueue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getServerQueue() {
        java.lang.Object ref = serverQueue_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          serverQueue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setServerQueue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serverQueue_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerQueue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serverQueue_ = getDefaultInstance().getServerQueue();
        onChanged();
        return this;
      }
      void setServerQueue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        serverQueue_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.openim.common.im.bean.protbuf.ConnectMessage)
    }
    
    static {
      defaultInstance = new ConnectMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.openim.common.im.bean.protbuf.ConnectMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_openim_common_im_bean_protbuf_ConnectMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_openim_common_im_bean_protbuf_ConnectMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ConnectMessage.proto\022!com.openim.commo" +
      "n.im.bean.protbuf\"H\n\016ConnectMessage\022\017\n\007l" +
      "oginId\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\023\n\013server" +
      "Queue\030\003 \001(\tB\030B\026ProtobufConnectMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_openim_common_im_bean_protbuf_ConnectMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_openim_common_im_bean_protbuf_ConnectMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_openim_common_im_bean_protbuf_ConnectMessage_descriptor,
              new java.lang.String[] { "LoginId", "Password", "ServerQueue", },
              com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage.class,
              com.openim.common.im.bean.protbuf.ProtobufConnectMessage.ConnectMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
