// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnLineMessage.proto

package com.openim.common.im.bean;

public final class ProtobufOnLineMessage {
  private ProtobufOnLineMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OnLineMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.openim.common.im.bean.OnLineMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string loginId = 5;</code>
     */
    boolean hasLoginId();
    /**
     * <code>optional string loginId = 5;</code>
     */
    java.lang.String getLoginId();
    /**
     * <code>optional string loginId = 5;</code>
     */
    com.google.protobuf.ByteString
        getLoginIdBytes();

    /**
     * <code>optional string pwd = 6;</code>
     */
    boolean hasPwd();
    /**
     * <code>optional string pwd = 6;</code>
     */
    java.lang.String getPwd();
    /**
     * <code>optional string pwd = 6;</code>
     */
    com.google.protobuf.ByteString
        getPwdBytes();

    /**
     * <code>optional string serverQueue = 7;</code>
     */
    boolean hasServerQueue();
    /**
     * <code>optional string serverQueue = 7;</code>
     */
    java.lang.String getServerQueue();
    /**
     * <code>optional string serverQueue = 7;</code>
     */
    com.google.protobuf.ByteString
        getServerQueueBytes();
  }
  /**
   * Protobuf type {@code com.openim.common.im.bean.OnLineMessage}
   */
  public static final class OnLineMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.openim.common.im.bean.OnLineMessage)
      OnLineMessageOrBuilder {
    // Use OnLineMessage.newBuilder() to construct.
    private OnLineMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OnLineMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OnLineMessage defaultInstance;
    public static OnLineMessage getDefaultInstance() {
      return defaultInstance;
    }

    public OnLineMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OnLineMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              loginId_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              pwd_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              serverQueue_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.openim.common.im.bean.ProtobufOnLineMessage.internal_static_com_openim_common_im_bean_OnLineMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.openim.common.im.bean.ProtobufOnLineMessage.internal_static_com_openim_common_im_bean_OnLineMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage.class, com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<OnLineMessage> PARSER =
        new com.google.protobuf.AbstractParser<OnLineMessage>() {
      public OnLineMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OnLineMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OnLineMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LOGINID_FIELD_NUMBER = 5;
    private java.lang.Object loginId_;
    /**
     * <code>optional string loginId = 5;</code>
     */
    public boolean hasLoginId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string loginId = 5;</code>
     */
    public java.lang.String getLoginId() {
      java.lang.Object ref = loginId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string loginId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLoginIdBytes() {
      java.lang.Object ref = loginId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PWD_FIELD_NUMBER = 6;
    private java.lang.Object pwd_;
    /**
     * <code>optional string pwd = 6;</code>
     */
    public boolean hasPwd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string pwd = 6;</code>
     */
    public java.lang.String getPwd() {
      java.lang.Object ref = pwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pwd = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPwdBytes() {
      java.lang.Object ref = pwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERQUEUE_FIELD_NUMBER = 7;
    private java.lang.Object serverQueue_;
    /**
     * <code>optional string serverQueue = 7;</code>
     */
    public boolean hasServerQueue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string serverQueue = 7;</code>
     */
    public java.lang.String getServerQueue() {
      java.lang.Object ref = serverQueue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverQueue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serverQueue = 7;</code>
     */
    public com.google.protobuf.ByteString
        getServerQueueBytes() {
      java.lang.Object ref = serverQueue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverQueue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      loginId_ = "";
      pwd_ = "";
      serverQueue_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(5, getLoginIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(6, getPwdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(7, getServerQueueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getLoginIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPwdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getServerQueueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.openim.common.im.bean.OnLineMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.openim.common.im.bean.OnLineMessage)
        com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.openim.common.im.bean.ProtobufOnLineMessage.internal_static_com_openim_common_im_bean_OnLineMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.openim.common.im.bean.ProtobufOnLineMessage.internal_static_com_openim_common_im_bean_OnLineMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage.class, com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage.Builder.class);
      }

      // Construct using com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        loginId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        serverQueue_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.openim.common.im.bean.ProtobufOnLineMessage.internal_static_com_openim_common_im_bean_OnLineMessage_descriptor;
      }

      public com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage getDefaultInstanceForType() {
        return com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage.getDefaultInstance();
      }

      public com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage build() {
        com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage buildPartial() {
        com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage result = new com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loginId_ = loginId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pwd_ = pwd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serverQueue_ = serverQueue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage) {
          return mergeFrom((com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage other) {
        if (other == com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage.getDefaultInstance()) return this;
        if (other.hasLoginId()) {
          bitField0_ |= 0x00000001;
          loginId_ = other.loginId_;
          onChanged();
        }
        if (other.hasPwd()) {
          bitField0_ |= 0x00000002;
          pwd_ = other.pwd_;
          onChanged();
        }
        if (other.hasServerQueue()) {
          bitField0_ |= 0x00000004;
          serverQueue_ = other.serverQueue_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.openim.common.im.bean.ProtobufOnLineMessage.OnLineMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object loginId_ = "";
      /**
       * <code>optional string loginId = 5;</code>
       */
      public boolean hasLoginId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string loginId = 5;</code>
       */
      public java.lang.String getLoginId() {
        java.lang.Object ref = loginId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            loginId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string loginId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLoginIdBytes() {
        java.lang.Object ref = loginId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string loginId = 5;</code>
       */
      public Builder setLoginId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        loginId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string loginId = 5;</code>
       */
      public Builder clearLoginId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loginId_ = getDefaultInstance().getLoginId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string loginId = 5;</code>
       */
      public Builder setLoginIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        loginId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pwd_ = "";
      /**
       * <code>optional string pwd = 6;</code>
       */
      public boolean hasPwd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string pwd = 6;</code>
       */
      public java.lang.String getPwd() {
        java.lang.Object ref = pwd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pwd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pwd = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPwdBytes() {
        java.lang.Object ref = pwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pwd = 6;</code>
       */
      public Builder setPwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pwd = 6;</code>
       */
      public Builder clearPwd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pwd_ = getDefaultInstance().getPwd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pwd = 6;</code>
       */
      public Builder setPwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pwd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serverQueue_ = "";
      /**
       * <code>optional string serverQueue = 7;</code>
       */
      public boolean hasServerQueue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string serverQueue = 7;</code>
       */
      public java.lang.String getServerQueue() {
        java.lang.Object ref = serverQueue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serverQueue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serverQueue = 7;</code>
       */
      public com.google.protobuf.ByteString
          getServerQueueBytes() {
        java.lang.Object ref = serverQueue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverQueue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serverQueue = 7;</code>
       */
      public Builder setServerQueue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serverQueue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverQueue = 7;</code>
       */
      public Builder clearServerQueue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serverQueue_ = getDefaultInstance().getServerQueue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverQueue = 7;</code>
       */
      public Builder setServerQueueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serverQueue_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.openim.common.im.bean.OnLineMessage)
    }

    static {
      defaultInstance = new OnLineMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.openim.common.im.bean.OnLineMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_openim_common_im_bean_OnLineMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_openim_common_im_bean_OnLineMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023OnLineMessage.proto\022\031com.openim.common" +
      ".im.bean\"B\n\rOnLineMessage\022\017\n\007loginId\030\005 \001" +
      "(\t\022\013\n\003pwd\030\006 \001(\t\022\023\n\013serverQueue\030\007 \001(\tB2\n\031" +
      "com.openim.common.im.beanB\025ProtobufOnLin" +
      "eMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_openim_common_im_bean_OnLineMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_openim_common_im_bean_OnLineMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_openim_common_im_bean_OnLineMessage_descriptor,
        new java.lang.String[] { "LoginId", "Pwd", "ServerQueue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
